name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  undercover:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run rspec
        run: bundle exec rspec

      - name: Run undercover
        run: bundle exec undercover --compare 1cec4ece7d32cae864da8c062453969e7976b24b
